const list = [
    {
      id: 1,
      title: "Banana da Terra",
      author: "Fruta Orgânica",
      price: 24,
      img: "https://www.clinicalivon.com.br/clinicalivon/wp-content/uploads/2014/05/Bananas.jpg",
      qtd: 20,
      amount: 1,
    },
    {
      id: 2,
      title: "Laranja Bahia",
      author: "Fruta Orgânica",
      price: 19,
      img: "https://citrusbr.com/wp-content/uploads/2021/04/laranjas.jpg",
      qtd: 20,
      amount: 1,
    },
    {
      id: 3,
      title: "Melância Com Semente",
      author: "Fruta Orgânica",
      price: 29,
      img: "https://atacarejoibatiba.com.br/wp-content/uploads/2017/10/melancia.png",
      qtd: 9,
      amount: 1,
    },
    {
      id: 4,
      title: "Morangos Camarosa",
      author: "Fruta Orgânica",
      price: 9,
      img: "https://hccariquemes.com.br/noticias/sem-titulo-1fw_14-33-30.png",
      qtd: 20,
      amount: 1,
    },
    {
      id: 5,
      title: "Tomate Caqui",
      author: "Fruta Orgânica",
      price: 4,
      img: "http://chc.org.br/wp-content/uploads/2015/05/imagem-1.jpg",
      qtd: 20,
      amount: 1,
    },
    {
      id: 6,
      title: "Batata Doce Roxa",
      author: "Legume Orgânico",
      price: 17,
      img: "http://chc.org.br/wp-content/uploads/2015/05/imagem-5.jpg",
      qtd: 10,
      amount: 1,
  },
];

export default list;